version: 2
jobs:
  kuromoji:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx4000m
      MAVEN_OPTS: -Xmx4000m
      TERM: dumb
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          keys:
            - kuromoji-build-{{ checksum "kuromoji/pom.xml" }}
            - kuromoji-build-
      - run: ls kuromoji/*/target/*.jar || (cd kuromoji && mvn clean package -DskipTests=true -pl kuromoji-ipadic-neologd -am -B -V)
      - save_cache:
          paths:
            - ~/repo/kuromoji
          key: kuromoji-build-{{ checksum "kuromoji/pom.xml" }}
      - persist_to_workspace:
          root: kuromoji
          paths:
            - kuromoji-core/target
            - kuromoji-ipadic-neologd/target
  build-es5.6.5: &build-template
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx4000m
      TERM: dumb
      ELASTICSEARCH_VERSION: 5.6.5
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/kuromoji
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build -Pelasticsearch_version="${ELASTICSEARCH_VERSION}"
      - persist_to_workspace:
          root: build
          paths:
            - distributions
  build-es5.6.4:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.6.4
  build-es2.6.4:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 2.6.4
  build-es5.6.3:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.6.3
  build-es5.5.2:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.5.2
  build-es5.5.1:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.5.1
  build-es5.5.0:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.5.0
  build-es2.4.5:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 2.4.5
  build-es5.4.3:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.4.3
  build-es5.4.2:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.4.2
  build-es5.4.0:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.4.0
  build-es1.7.6:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 1.7.6
  build-es5.3.2:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.3.2
  build-es5.3.1:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.3.1
  build-es2.4.4:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 2.4.4
  build-es5.3.0:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.3.0
  build-es5.2.2:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.2.2
  build-es5.2.1:
    <<: *build-template
    environment:
      ELASTICSEARCH_VERSION: 5.2.1
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/build
      - run: gradle githubRelease -Pversion="${CIRCLE_TAG#v}" -Pgithub_token="${GITHUB_TOKEN}"
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - kuromoji:
          filters:
            tags:
              only: /.*/
      - build-es5.6.5:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.6.4:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es2.6.4:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.6.3:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.5.2:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.5.1:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.5.0:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es2.4.5:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.4.3:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.4.2:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.4.0:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es1.7.6:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.3.2:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.3.1:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es2.4.4:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.3.0:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.2.2:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - build-es5.2.1:
          requires:
            - kuromoji
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build-es5.6.5
            - build-es5.6.4
            - build-es2.6.4
            - build-es5.6.3
            - build-es5.5.2
            - build-es5.5.1
            - build-es5.5.0
            - build-es2.4.5
            - build-es5.4.3
            - build-es5.4.2
            - build-es5.4.0
            - build-es1.7.6
            - build-es5.3.2
            - build-es5.3.1
            - build-es2.4.4
            - build-es5.3.0
            - build-es5.2.2
            - build-es5.2.1
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
