version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx4000m
      MAVEN_OPTS: -Xmx4000m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - kuromoji-build-{{ (cd kuromoji && git rev-parse HEAD) }}
      - run: ls kuromoji/*/taeget/*.jar || (git submodule update --init --recursive && cd kuromoji && mvn clean package -DskipTests=true -pl kuromoji-ipadic-neologd -am -B -V)
      - save_cache:
          paths:
            - ~/repo/kuromoji
          key: kuromoji-build-{{ git rev-parse HEAD }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/repo/kuromoji
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - persist_to_workspace:
          root: build
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
      - run: gradle githubRelease -Pversion=0.0.1
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
