version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx4000m
      MAVEN_OPTS: -Xmx4000m
      TERM: dumb
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          keys:
            - kuromoji-build-{{ checksum "kuromoji/pom.xml" }}
      - run: ls kuromoji/*/target/*.jar || (cd kuromoji && mvn clean package -DskipTests=true -pl kuromoji-ipadic-neologd -am -B -V)
      - save_cache:
          paths:
            - ~/repo/kuromoji
          key: kuromoji-build-{{ checksum "kuromoji/pom.xml" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/repo/kuromoji
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - persist_to_workspace:
          root: build
          paths:
            - distributions
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/build
      - run: gradle githubRelease -Pversion="${CIRCLE_TAG#v}"
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
